AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-nodejs16.x

  Sample SAM Template for lambda-nodejs16.x
  
Globals:
  Function:
    Timeout: 30
    Architectures:
      - x86_64

Resources:
  GetYoutubeCaption:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/getYoutubeCaption/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
  SummaryTest:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/summaryTest/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
